export const LIGHT_THEME = 'LIGHT_THEME';
export const DARK_THEME = 'DARK_THEME';
export const NAVIGATION_TYPE_VERTICAL = 'VERTICAL';
export const NAVIGATION_TYPE_HORIZONTAL = 'ORIZONTAL';
export const NAVIGATION_TYPE_COMBO = 'COMBO';
export const VERTICAL_NAVBAR_APPEARANCE_DEFAULT = 'DEFAULT';
export const VERTICAL_NAVBAR_APPEARANCE_LIGHTER = 'LIGHTER';
export const VERTICAL_NAVBAR_APPEARANCE_DARKER = 'DARKER';
export const HORIZONTAL_NAVBAR_SHAPE_DEFAULT = 'DEFAULT';
export const HORIZONTAL_NAVBAR_SHAPE_SLIM = 'SLIM';
export const HORIZONTAL_NAVBAR_APPEARANCE_DEFAULT = 'DEFAULT';
export const HORIZONTAL_NAVBAR_APPEARANCE_LIGHTER = 'LIGHTER';
export const HORIZONTAL_NAVBAR_APPEARANCE_DARKER = 'DARKER';

export const LANGUAGE_VIETNAMESE = 'vi';
export const LANGUAGE_ENGLISH = 'en';

export const NO_REQUEST = 'NO_REQUEST';
export const REJECTED = 'REJECTED';
export const PENDING = 'PENDING';
export const FULFILLED = 'FULFILLED';
